import { Doctor, Medicine, LabTest, MealPlan, Meal, LabResult } from '@/types';

export const mockDoctors: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Adebayo Okonkwo',
    specialty: 'Cardiologist',
    rating: 4.9,
    reviews: 234,
    experience: 15,
    avatar: 'https://i.pravatar.cc/150?img=12',
    availability: 'available',
    consultationFee: 5000,
    languages: ['English', 'Yoruba', 'Igbo'],
    bio: 'Specialized in cardiovascular diseases with over 15 years of experience.',
  },
  {
    id: '2',
    name: 'Dr. Chioma Nwankwo',
    specialty: 'Pediatrician',
    rating: 4.8,
    reviews: 189,
    experience: 10,
    avatar: 'https://i.pravatar.cc/150?img=45',
    availability: 'available',
    consultationFee: 4500,
    languages: ['English', 'Igbo'],
    bio: 'Passionate about child healthcare and development.',
  },
  {
    id: '3',
    name: 'Dr. Ibrahim Musa',
    specialty: 'General Practitioner',
    rating: 4.7,
    reviews: 156,
    experience: 8,
    avatar: 'https://i.pravatar.cc/150?img=33',
    availability: 'busy',
    consultationFee: 3500,
    languages: ['English', 'Hausa'],
    bio: 'Providing comprehensive primary healthcare services.',
  },
  {
    id: '4',
    name: 'Dr. Amara Eze',
    specialty: 'Dermatologist',
    rating: 4.9,
    reviews: 278,
    experience: 12,
    avatar: 'https://i.pravatar.cc/150?img=44',
    availability: 'available',
    consultationFee: 6000,
    languages: ['English', 'Igbo'],
    bio: 'Expert in skin conditions and cosmetic dermatology.',
  },
];

export const mockMedicines: Medicine[] = [
  {
    id: '1',
    name: 'Paracetamol 500mg',
    description: 'Pain reliever and fever reducer',
    price: 500,
    category: 'Pain Relief',
    manufacturer: 'GSK',
    requiresPrescription: false,
    inStock: true,
    dosage: '1-2 tablets every 4-6 hours',
  },
  {
    id: '2',
    name: 'Amoxicillin 500mg',
    description: 'Antibiotic for bacterial infections',
    price: 1200,
    category: 'Antibiotics',
    manufacturer: 'Pfizer',
    requiresPrescription: true,
    inStock: true,
    dosage: '1 capsule 3 times daily',
  },
  {
    id: '3',
    name: 'Lisinopril 10mg',
    description: 'Blood pressure medication',
    price: 2500,
    category: 'Cardiovascular',
    manufacturer: 'AstraZeneca',
    requiresPrescription: true,
    inStock: true,
    dosage: '1 tablet once daily',
  },
  {
    id: '4',
    name: 'Multivitamin',
    description: 'Daily vitamin supplement',
    price: 3500,
    category: 'Supplements',
    manufacturer: 'Nature\'s Bounty',
    requiresPrescription: false,
    inStock: true,
    dosage: '1 tablet daily',
  },
  {
    id: '5',
    name: 'Insulin Glargine',
    description: 'Long-acting insulin',
    price: 8500,
    category: 'Diabetes',
    manufacturer: 'Sanofi',
    requiresPrescription: true,
    inStock: true,
    dosage: 'As prescribed by doctor',
  },
];

export const mockLabTests: LabTest[] = [
  {
    id: '1',
    name: 'Complete Blood Count (CBC)',
    description: 'Measures different components of blood',
    price: 3500,
    preparationRequired: false,
    estimatedTime: '24 hours',
    category: 'Blood Tests',
  },
  {
    id: '2',
    name: 'Lipid Profile',
    description: 'Cholesterol and triglycerides test',
    price: 4500,
    preparationRequired: true,
    preparationInstructions: 'Fasting for 12 hours required',
    estimatedTime: '48 hours',
    category: 'Blood Tests',
  },
  {
    id: '3',
    name: 'Blood Glucose Test',
    description: 'Measures blood sugar levels',
    price: 1500,
    preparationRequired: true,
    preparationInstructions: 'Fasting for 8 hours required',
    estimatedTime: '24 hours',
    category: 'Blood Tests',
  },
  {
    id: '4',
    name: 'Thyroid Function Test',
    description: 'Checks thyroid hormone levels',
    price: 5500,
    preparationRequired: false,
    estimatedTime: '48 hours',
    category: 'Hormone Tests',
  },
  {
    id: '5',
    name: 'Liver Function Test',
    description: 'Assesses liver health',
    price: 6000,
    preparationRequired: false,
    estimatedTime: '24 hours',
    category: 'Organ Function',
  },
];

export const mockMeals: Meal[] = [
  {
    id: '1',
    name: 'Grilled Chicken & Vegetables',
    description: 'Lean protein with colorful roasted vegetables',
    calories: 450,
    mealType: 'lunch',
    ingredients: ['Chicken breast', 'Bell peppers', 'Broccoli', 'Olive oil'],
  },
  {
    id: '2',
    name: 'Oatmeal with Berries',
    description: 'Wholesome breakfast with fresh fruits',
    calories: 320,
    mealType: 'breakfast',
    ingredients: ['Oats', 'Blueberries', 'Strawberries', 'Honey', 'Almonds'],
  },
  {
    id: '3',
    name: 'Salmon & Quinoa Bowl',
    description: 'Omega-3 rich salmon with quinoa and greens',
    calories: 520,
    mealType: 'dinner',
    ingredients: ['Salmon fillet', 'Quinoa', 'Spinach', 'Lemon', 'Avocado'],
  },
];

export const mockMealPlans: MealPlan[] = [
  {
    id: '1',
    name: 'Weight Loss Plan',
    description: 'Balanced meals designed for healthy weight loss',
    calories: 1500,
    protein: 120,
    carbs: 150,
    fats: 50,
    meals: mockMeals,
    duration: 30,
    price: 45000,
  },
  {
    id: '2',
    name: 'Muscle Gain Plan',
    description: 'High protein meals for muscle building',
    calories: 2500,
    protein: 200,
    carbs: 250,
    fats: 80,
    meals: mockMeals,
    duration: 30,
    price: 55000,
  },
  {
    id: '3',
    name: 'Heart Healthy Plan',
    description: 'Low sodium, omega-3 rich meals',
    calories: 1800,
    protein: 100,
    carbs: 180,
    fats: 60,
    meals: mockMeals,
    duration: 30,
    price: 50000,
  },
];

export const mockLabResults: LabResult[] = [
  {
    id: '1',
    testId: '1',
    testName: 'Complete Blood Count (CBC)',
    date: '2025-10-28',
    results: [
      { parameter: 'Hemoglobin', value: '14.5', normalRange: '12-16 g/dL', status: 'normal' },
      { parameter: 'White Blood Cells', value: '7.2', normalRange: '4-11 x10^9/L', status: 'normal' },
      { parameter: 'Platelets', value: '250', normalRange: '150-400 x10^9/L', status: 'normal' },
    ],
    doctorNotes: 'All parameters within normal range. Continue current medications.',
  },
];
